# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0030_auto_20171218_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.ProjectLocatie')),
            ],
            options={
                'ordering': ('order', 'location'),
            },
        ),
    ]
